### ISSUE TITLE
Hi, question 

### ISSUE THREAD

**Issue by iShift** [mooyoul/node-kiturami#1]
Hi, what kiturami model do you have? i have twin alpha and i try to find solution to work with node-kiturami 
![899f02241a6e2ca80dea7b4e13a4dda3](https://cloud.githubusercontent.com/assets/426427/21311824/49d5ea98-c5fa-11e6-96db-7bdfa19689b6.jpg)

**Comment by mooyoul** [comment]
Hi @iShift !

Currently i'm using *4번 타는 귀뚜라미 보일러* (sorry for Korean model name). I took a photo, see below:
![dsc06483](https://cloud.githubusercontent.com/assets/2101743/21461082/93188d38-c991-11e6-99d8-78debbbadf28.jpg)

and boiler connected with CTR-5700PLUS controller before (see below)
![ctr-5700plus](https://mooyoul.github.io/2016/11/06/installing-kiturami-iot-heating-controller/DSC06523.jpg)

and there is a [blog post about my installation and some researches](https://mooyoul.github.io/2016/11/06/installing-kiturami-iot-heating-controller/) (in Korean)

You will need to buy NCTR-10WIFI (순간식 - *instant type* in Korean) controller. 
Kiturami says 트윈알파 (*Twin Alpha* in Korean) is compatible with 'NCTR-10WIFI 순간식' controller.

You can buy this controller on [Kiturami Official Store](http://www.11st.co.kr/product/SellerProductDetail.tmall?method=getSellerProductDetail&prdNo=1368878810).

But i can't ensure this controller is compatible with boilers in outside of Korea.
and Timezone of clock on NCTR-10WIFI seems supporting GMT+9 (Seoul) only.

If you have any question, please feel free to reply.
Thanks!
